[package]
name = "rust_bin"
version = "0.1.0"
authors = ["Garrett Squire <github@garrettsquire.com>"]
edition = "2018"

[dependencies]
rocket = "0.4"
rocket_contrib = { version = "0.4", default-features = false, features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
